### ISSUE TITLE
Phil The Hacker

### ISSUE THREAD

**Issue by SLG64** [ipodtouch0218/NSMB-MarioVsLuigi#106]
So, There is Phil, and I didn't mind him in the past. He used to spawn stars after the game or make people mega and everyone was big. Sadly, Phil has had too much fun and has started duplicating himself, making his name too big for anyone to play, killing everyone on screen, and the duplication causes lag. He is even able to join into lobbies after the game has started, (I think) kick others, and change the map. 

If anyone finds him in their lobby, please copy his player ID and type in the replies. 

      Thank You!

![Screenshot 2022-09-02 8 57 06 AM (1)](https://user-images.githubusercontent.com/112098393/188665759-b40ad6f6-25ff-40d5-955f-a61610b785a6.png)

P.S.  Phil, If you're reading this, I really don't mean to be rude, but this needs to stop.

**Comment by Mardz38** [comment]
Have you ever heard of private lobbies?

**Comment by Foxxy-01** [comment]
> Have you ever heard of private lobbies?

Hackers can see private lobbies I believe if they do some stuff lol

**Comment by SLG64** [comment]
As I said, they can join games even if it's already started.

**Comment by SLG64** [comment]
So, it makes perfect sense they can hack into private lobbies.

**Comment by evancgassman** [comment]
I think you need to learn more about GitHub issues before creating them. This isn't an issue? You literally explained an informative announcement.

**Comment by SLG64** [comment]
Well, I'm just saying that if you find Phil in your lobby, put his user ID here. ipodtouch0218 literally joined my lobby and told us to put his user ID here.

**Comment by ipodtouch0218** [comment]
We already know who Phil was, and they've been banned from both the discord and the game.
