### ISSUE TITLE
Super Mushroom Turns You Into Super Mario/Luigi When Powered Up As Anything Else

### ISSUE THREAD

**Issue by SLG64** [ipodtouch0218/NSMB-MarioVsLuigi#107]
I don't know if it's just a Mini Mushroom hidden from view behind a Super Mushroom, or if it's a glitch.

**Comment by Proxofer** [comment]
thats not a bug, the super mushroom is supposed make you big, no matter what powerup you use

**Comment by SLG64** [comment]
So when you're Fire Mario/Luigi, you are supposed to be reverted back to Super Mario/Luigi?

**Comment by FiveSpade** [comment]
> So when you're Fire Mario/Luigi, you are supposed to be reverted back to Super Mario/Luigi?

Yeah this is how it works in the original game

**Comment by SLG64** [comment]
So if you are powered up as Fire Mario/Luigi, and a Super Mushroom touches you, you're supposed to revert to Super Mario/Luigi? I have a feeling that it's just a Mini Mushroom hidden behind the Super Mushroom.

**Comment by Proxofer** [comment]
sure, but it is supposed to be like that, like picking any other powerup different from the current powerup you are using, you will always turn into the powerup you pick up. example: You have the fire powerup, picking up shell, fly mushroom of the ice flower makes update into that powerup you pick up. same goes for the super mushroom, only difference is that in super mushroom your old powerup will NOT save inside your inventory.

**Comment by Proxofer** [comment]
now please, just accept this. literally EVERY powerup almost behaves the same with changing

**Comment by SLG64** [comment]
So you should become Super Mario/Luigi when you grab a Super Mushroom as Fire Mario/Luigi or anything besides Mini Mushroom?!?!?

**Comment by Syrinaxis123** [comment]
yeah because that’s how it works in other games with the mega mushroom

**Comment by SLG64** [comment]
I was talking about everything besides the Mini Mushroom and Mega Mushroom.

**Comment by ipodtouch0218** [comment]
Couldn't reproduce? The mushroom goes into the reserve slot if it's open, as expected. Most likely had a mini mushroom behind the super mushroom, super easy to have happen in monocoin games.

**Comment by SLG64** [comment]
Thank you for confirming.
