### ISSUE TITLE
Sonic/Blaze

### ISSUE THREAD

**Issue by Foxxy-01** [ipodtouch0218/NSMB-MarioVsLuigi#110]
Adding Sonic and/or Blaze from Sonic Rush Would add a bit of variety and uniqueness to the game and it would also be really cool if there was a toggleable option (host side) that enabled Sonic Rush Physics (players as sonic) with spindashing and such, as you can tell, I am a huge Sonic Fan and I would love it if you added this, though I'm not entirely sure how powerups would work... mabye fire dash powerup (fire shield but without the shield part) the bubble powerup (the one that let's you breathe lol but without the shield part) and the Invincibilty powerup and also a altered mega mushroom powerup that would make you bigger but not as big as the Mario one, but still quite big. And replacements for the ice flower and such I can't really think of ideas for so if anybody would like to help would be appreciated oh and also in water stages *insert troll face here* you. can. drown. I am horrible at C# so I have no idea how easy these will be to add but I know it may be hard so uhh yeaaaaaaaa............. lmao but uhhhhhhh pog oh and also the invincibility powerup should use silvagunners Sonic invincibility Mario remix (with permission of course) if permission is unobtainable try Sonic 3&K invincibility, here is a link to the Sonic Invincibility Mario thingy remix https://youtu.be/4NWiDUEnCYk and here is a link the Sonic 3&K invincibility https://youtu.be/N6YqH9mKjv8

Oh and also forgot to mention that Mario's and Sonic's/Blaze can be in the same world just that Sonic/Blaze's Physics only apply to Sonic/Blaze

Also my idea is probally quite unbalanced or something but if not pog, if it is then feel free to suggest ideas and balancing and stuff

**Comment by Foxxy-01** [comment]
K but people can still add stuff so there's always a chance, plus no need to type that when your input about that literally changes nothing...

**Comment by Foxxy-01** [comment]
K but people can still add stuff so there's always a chance, plus no need to type that when your input about that literally changes nothing...

**Comment by evancgassman** [comment]
This doesn't seem like a smart idea. The game (for the most part with the exception of custom stages) is supposed to be based off of the original. If you would want to see something like this, then possibly make a Branch, and create your own "mod".

**Comment by SLG64** [comment]
I mean, you could put some Sonic "Easter eggs"?

**Comment by evancgassman** [comment]
Nope.

**Comment by SLG64** [comment]
No not  this game, dummy. In their mod.

**Comment by Mardz38** [comment]
Okay, then discuss it somewhere else and not here.

**Comment by SLG64** [comment]
Hey, I'm not a Sonic Fan. I was suggesting something for them. You don't have to reply, you know.

**Comment by Mardz38** [comment]
Hey, I don't remember asking. You don't have to reply, you know. I'm not trying to be mean. 

This is a Mario game. If Sonic gets added I'll eat my hat.

**Comment by SLG64** [comment]
Ok, then. Glad that we're good again.

**Comment by Mardz38** [comment]
What.

**Comment by SLG64** [comment]
nevermind

**Comment by ipodtouch0218** [comment]
This goes against the authenticity that I want to preserve in the game, being an expanded, but still plausibly official, version of MvL.

Radically different characters isn't something that would benefit the game regardless, in my opinion.
