### ISSUE TITLE
New Maps?

### ISSUE THREAD

**Issue by SLG64** [ipodtouch0218/NSMB-MarioVsLuigi#114]
I am not very skilled at coding or anything, and I don't care if I'm told again that this is for issues. I would like more maps. I think The Cutting Room Floor has some good maps. Here are a some, and I'll add more later:
file:///home/chronos/u-639649e1e209099531d3e0784a1230b204c9b951/MyFiles/Downloads/Fortress2.png

**Comment by evancgassman** [comment]
Why do you keep shit-posting in the issues tab?

**Comment by SLG64** [comment]
Because I can do what I want, I live in America.

**Comment by SLG64** [comment]
And I cannot get into discord for some reason. So, if you want to get shitty with me, I'd advise you not to.

**Comment by TBiscuit1** [comment]
bro is lowkey treatening someone for asking them to stop shooting shitty suggestion that got request 20x

No shit you got kicked out of the discord

**Comment by SLG64** [comment]
I never joined the discord, so jokes on you.
![DeadLuigi(SM64Beta)](https://user-images.githubusercontent.com/112098393/190238188-cb89596f-8507-4592-8e7e-99d577e7ed6b.jpg)

**Comment by abso1utezer0** [comment]
While the author has been annoying on the issues lately, this isn't a shitty or awful idea, but it is pretty vague.

**Comment by Omega207** [comment]
Why are you bothering the game creator with this? If you don't know how to code, LEARN TO CODE. Surely, your brain can understand how to code. And what's the point of a GitHub account if you're not going to code anything in the first place?
Surely not a lot of people can stand being spammed with questions about what they're going to do in the game.
How would you feel if you spent months working on a game, only to be spammed by others to force add stuff to your game?
All I'm saying is, you're NOT talking to a brick wall which can take as many spammy hits as possible. These are people who probably put a lot out of their life to make sure this game could be good.
Don't force, please. If you want to help, make it yourself.

**Comment by SLG64** [comment]
Hey, thanks for your feedback. I know that they have to fix plenty of things, but I won't pester them with making the new maps or adding features. These are just suggestions for when they have nothing to do or are interested in adding something new.

**Comment by Omega207** [comment]
Ah, thank you for clarifying.
I apologize for my quick actions without much thought.
In that case, it would probably be good to add more maps from NSMB (or maybe others from other New Super Mario Bros. games).

**Comment by SLG64** [comment]
I agree, and thank you for apoligizing. I can be a little annoying at times, but I am mostly only trying to be useful, mainly by giving out ideas.

**Comment by Foxxy-01** [comment]
> I agree, and thank you for apoligizing. I can be a little annoying at times, but I am mostly only trying to be useful, mainly by giving out ideas.

I am kinda the same lol and I got banned of suggesting ideas on the discord for posting sonic suggestion 💀

**Comment by SLG64** [comment]
Reasonable. I never joined it, so I can't speak.

**Comment by ipodtouch0218** [comment]
> file:///home/chronos/u-639649e1e209099531d3e0784a1230b204c9b951/MyFiles/Downloads/Fortress2.png

Once again, this is a local file and we're unable to see it.

Obviously new maps will be included in due time, but there aren't any planned for v1.8.0.0-beta. Quality > Quantity.

**Comment by ipodtouch0218** [comment]
Closing as invalid

**Comment by ipodtouch0218** [comment]
Closed as invalid.
