### ISSUE TITLE
I saw a Sewer map in Pull requests and just wanted to reiterate how its a garbage map 

### ISSUE THREAD

**Issue by FiveSpade** [ipodtouch0218/NSMB-MarioVsLuigi#120]
Nope this sewer Map would be absolutely garbage, imma just list the reason its garbage in bullets
Tight low ceiling areas make it very fire flower centric with jumping on head not being worth doing (ie it will be super annoying to play on)
All the different elevation changes with small opening makes it EVEN MORE fireflower centric because people can easily control huge portions of the map by spamming a button
-Overall map looks boring and doesnt have any outstanding elements that make it fun to play on
-Where do you put stars that doesnt make them super luck based (with so many sectioned off areas it makes getting stars seem super luck based cause they could just spawn in a diff section and you have no chance of getting it)
-Map (at top of screen) with be stupidly confusing ("is that star on the highest level or is it 2 levels down?")
-Cool concept but in theory without some major reworks would be a disgusting map to play on

**Comment by ipodtouch0218** [comment]
Closed. Please comment on the pull request (#56), rather than in a separate issue.
