### ISSUE TITLE
Please distribute the server code

### ISSUE THREAD

**Issue by suchipi** [ipodtouch0218/NSMB-MarioVsLuigi#128]
It's only a matter of time before this gets DMCA'd... please distribute the backend code before then so people can continue to play afterwards (by hosting their own servers)

**Comment by Kibahor** [comment]
I totally agree, in one side in case of DMCA, the game will continue to exists and it will enable people to enhance the code by optimizing, correcting and suggest features.

**Comment by Foxxy-01** [comment]
Agreed 👍

**Comment by ipodtouch0218** [comment]
The game uses Photon, where the servers only deal with matchmaking / proxying. The only server side code is the authentication server, which can be disabled pretty simply when connecting to your own servers through Photon. There's no "server side code" to speak of.

**Comment by Kibahor** [comment]
Ok thanks for clarify the misunderstanding

**Comment by suchipi** [comment]
Thanks! Sorry for the confusion.
