### ISSUE TITLE
Certain items not appearing

### ISSUE THREAD

**Issue by dvk-wow** [ipodtouch0218/NSMB-MarioVsLuigi#129]
Unsure if this is intentional or not, and I don't know if that's also a problem for public lobbies, but when I play in private with my friends, no matter what happens, invincibility stars and mega mushrooms do not appear.

**Comment by ipodtouch0218** [comment]
Item spawn rates were rebalanced in 1.7.1.0-beta. Item spawns now depend on the amount of stars you're playing to. You're probably playing to 99 stars (for whatever godforsaken reason), meaning that starmen/megamushrooms will only start spawning after the leading player collects around ~10/15 stars. This is to avoid starmen/megamushrooms spawning at the beginning of normal games.

If you're really insistent on playing deathmatch, set the number to something more reasonable (like 50 or 35).

**Comment by SLG64** [comment]
I think it's more resonable due to the fact that it's "Frantic Items" not appearing until someone's about to win.

**Comment by ipodtouch0218** [comment]
Closed due to inactivity
