### ISSUE TITLE
MacOS build executable has incorrect permissions

### ISSUE THREAD

**Issue by Ndymario** [ipodtouch0218/NSMB-MarioVsLuigi#13]
Attempting to run the .app as-is will result in an error. To fix this, change the executable's permissions (using chmod) to allow for the program to be executed.

**Comment by ipodtouch0218** [comment]
Not sure if it's possible to use chmod on windows (even via WSL) to mark it as executable in a completely different file system. Sorta unsolvable?

**Comment by Ndymario** [comment]
Yeah, that should work since all you need to do is run CHMOD. I'll look into the minimum required permissions for this to run on MacOS to prevent any issues where if someone wanted to play but lacked sudo permissions.

**Comment by Ndymario** [comment]
Alternatively, we could make a Git Action to run a script every time a build is uploaded. 🤔

I can test the build once I get home.

**Comment by ipodtouch0218** [comment]
If it's possible to get Git Actions to modify release builds, we could do that. alternatively, we could just add it to the build script that @TheMoogle made.

Just that Git Actions runs on linux distros, and there might not be a simple equivalent for marking a file already WITHIN a zip, without extracting it?

**Comment by ipodtouch0218** [comment]
@Ndymario If you're able to, could you check if the [v1.6.7.0-beta](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/releases/tag/v1.6.7.0-beta) builds are able to be opened without using chmod?

**Comment by Ndymario** [comment]
I can when I get off work 👍🏻

**Comment by Ndymario** [comment]
It seems this issue has been resolved!
