### ISSUE TITLE
Windows 7 64 bit users not connecting to the auth servers properly

### ISSUE THREAD

**Issue by Syrinaxis123** [ipodtouch0218/NSMB-MarioVsLuigi#132]
When opened, it doesn’t respond and is forced to close.

**Comment by ipodtouch0218** [comment]
This was a known issue fixed in [1.7.1.0-beta. Make sure you're using the latest version.](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/releases/latest)

**Comment by ipodtouch0218** [comment]
Closed as invalid.
