### ISSUE TITLE
MacOS: Black screen but audio works

### ISSUE THREAD

**Issue by DjPower353** [ipodtouch0218/NSMB-MarioVsLuigi#133]
when i open the game i get a black screen with only the music

**Comment by ipodtouch0218** [comment]
Your graphics card / macOS version is too old to run the game. If you check your player.log, you'll see that it fails to load shaders due to your graphics card being outdated.

You can try updating your graphics drivers or macOS version, no guarantees though.

**Comment by ipodtouch0218** [comment]
Closing as stale.
