### ISSUE TITLE
Feature Request:  Add a Boss Mode

### ISSUE THREAD

**Issue by ghost** [ipodtouch0218/NSMB-MarioVsLuigi#135]
Here's a great idea for a feature to be added in the next update: A boss mode. Players can face off against Bowser (single or multiplayer) and the first person to beat Bowser wins. And powerups can spawn through pipes infinitely so no one dies immediately.
Reply to this issue if you think this is a great idea!

**Comment by SLG64** [comment]
I think it sounds interesting. I keep thinking of a 3D mode for some reason...

**Comment by ipodtouch0218** [comment]
A boss mode goes against the core idea of the project, namely being a PvP gamemode.
