### ISSUE TITLE
cant download on chromebook

### ISSUE THREAD

**Issue by Kirby77428** [ipodtouch0218/NSMB-MarioVsLuigi#139]
can you help me figure out this issue so i can play the game on my chromebook pls?
its just not working :(

[Screen recording 2022-10-21 5.31.55 PM.webm](https://user-images.githubusercontent.com/116392124/197292011-39ef7250-7478-403b-a060-ac120a591bfd.webm)

**Comment by ipodtouch0218** [comment]
Chromebooks are a very locked down ecosystem, and don't natively support running arbitrary executables without Linux mode (in newer chromebooks) or dual booting.

I'd recommend just using the [itch.io version](https://ipodtouch0218.itch.io/NSMB-MarioVsLuigi) instead.

**Comment by SLG64** [comment]
Is there a way that you can add the game on a website that is not itch.io? I cannot access it anymore, and I have no clue how to play it now.

**Comment by ipodtouch0218** [comment]
@SLG64 
I keep a mirror of the webgl version at [ipodtouch0218.itch.io](https://ipodtouch0218.github.io). Please don't post on unrelated issues.
