### ISSUE TITLE
suggestion/feature: Nintendo DS deport -- With example concept with how to setup

### ISSUE THREAD

**Issue by EpicDoodleboy2** [ipodtouch0218/NSMB-MarioVsLuigi#143]
It would be cool to have NSMB multiplayer playing on a authentic system that was made for it and could be done via a replacement server for WFC Wiimmfi (that revives DS + WII's online multiplayer) 
it would connect to that server then connect to yours (maybe add DSI Enhanced WI-FI capabilities)

-- Example-- how to setup concept

1.A patch installer to a patch a rom of NSMB (Pick E, U or J Roms) When finished put it in the SD Card or a Pre-built NDS file
2.The data file from NSMB MVL put on the root of the SD Card
2.5. Eject and put in Flashcard or The DSI SD Card slot
3.Launch via a menu (E.x YSmenu and Twilight menu ++)
4.Then connect online with the Enhanced DSI Settings or The DS WI-FI Menu -- how to connect is at the bottom
4.5 if it Finds a update it updates
5.Play with PC players or DS players

-- if you want to connect online again check out this video by mrbean35000 https://www.youtube.com/watch?v=Sh0AZR-tKwM

**Comment by vlcoo** [comment]
Unfortunately, the original Mario vs Luigi mode of NSMB is not WFC based, but only local. So this won't be able to work without significant modifications to the ROM.

**Comment by EpicDoodleboy2** [comment]
Yeah, you got a point and that's why I put a patch installer First so It can add WFC server to Server connection in with its settings
(I know it's a concept of what to do)

**Comment by ipodtouch0218** [comment]
This really isn't within the scope of this remake. It's not possible to port a recent Unity game to a DS at all.
Closing as not planned.

**Comment by EpicDoodleboy2** [comment]
Should of thought of the 'new' 3ds....

**Comment by EpicDoodleboy2** [comment]
I should of thought of the 'New' 3DS
