### ISSUE TITLE
Turning items off and on and set how much will the item spawn (OPTION)

### ISSUE THREAD

**Issue by EpicDoodleboy2** [ipodtouch0218/NSMB-MarioVsLuigi#147]
Does people hate getting thrown off by 5 ice powered Mario or Luigi, well setting the number from 1-5 you'll see not that many ice flowers appear, or turn off items or a selection of items but not all because time outs become more apparent (maybe 1-3 items be off).

**Comment by ipodtouch0218** [comment]
Duplicate of #119
