### ISSUE TITLE
The remote server returned an error: 502 Bad Gateway

### ISSUE THREAD

**Issue by Ambijubi** [ipodtouch0218/NSMB-MarioVsLuigi#149]
![image](https://user-images.githubusercontent.com/95302846/206827512-8b34f4c9-9a70-45ea-96a6-cdb84301a3ec.png) I can't play my favorite game on Linux, because of this error.
OS:Ubuntu 22.04
Help, please!

**Comment by ipodtouch0218** [comment]
This is just an authentication server issue, it happens every once in a while. Closing, as it's currently fixed.
