### ISSUE TITLE
Luigi stays in ground pound animation with blue shell when in poison

### ISSUE THREAD

**Issue by LilMoINFINITY** [ipodtouch0218/NSMB-MarioVsLuigi#15]
when you get a blue shell and ground pound into the poison in the Custom Jungle stage, the character (either mario or luigi) stays in a normal ground pound animation, then goes in the shell when falling off-screen. this bug is only happening with the blue shell, not any other power up

**Comment by ipodtouch0218** [comment]
Confirmed.

**Comment by ipodtouch0218** [comment]
Fixed in release v1.5.4.0-beta
