### ISSUE TITLE
Cant Connect au servers

### ISSUE THREAD

**Issue by egGENGR** [ipodtouch0218/NSMB-MarioVsLuigi#150]
"user not authoriezed to join room" comes up whe  trying to connect in au server

**Comment by ipodtouch0218** [comment]
This happens when you're banned from a room, have too many connections on one IP address, or banned from the entire game. If none of these seem to be the case for you, let me know on the Discord in #technical-support, or at ipodtouch0218#0400

**Comment by ipodtouch0218** [comment]
Closing as stale. If this is still a problem, re-open this issue with more information.
