### ISSUE TITLE
You can shoot fireballs when dying from poison.

### ISSUE THREAD

**Issue by LilMoINFINITY** [ipodtouch0218/NSMB-MarioVsLuigi#16]
when in the death animation, fire mario/luigi can still shoot fireballs, and can hit other players

**Comment by ipodtouch0218** [comment]
Unconfirmed, make sure you're on the most recent version / playing on itch.io?

**Comment by LilMoINFINITY** [comment]
using 1.5.4.0-beta downloadable version from github

**Comment by ipodtouch0218** [comment]
Figured this out last night, only happens when shooting fireballs with the sprint key.

Confirmed.

**Comment by ipodtouch0218** [comment]
Fixed in release v1.6.0.0-beta
