### ISSUE TITLE
Hitbox error + Mario dying try to enter space where mini mario is required (CubbysCharacterMod)

### ISSUE THREAD

**Issue by Admant3x** [ipodtouch0218/NSMB-MarioVsLuigi#161]
Down below you can find 4 screenshot i made that describe the bug i encountered

**[BUG 1]**
**DYING TRYING EXITING MINI MARIO SPACE WHILE BUG 2 IS ACTIVE (FORTRESS MAP)****
![MvL-CubbysCharacterMod-106x93-08 19PM](https://user-images.githubusercontent.com/121366826/215343240-3676b579-0699-41f2-862f-a3216b411da9.png)

**[BUG 1-2]**
![MvL-CubbysCharacterMod-87x78-08 19PM](https://user-images.githubusercontent.com/121366826/215343243-26c08d9b-3f7e-4c6b-ac8b-4f7a816a7cee.png)

**[BUG 2]**
**THE ISSUE WITH THIS ONE IS THAT NORMAL MARIO CAN FIT IN MINI MARIO SPACE**
![MvL-CubbysCharacterMod-448x88-08 18PM](https://user-images.githubusercontent.com/121366826/215343242-491b1904-fb0f-433c-b568-0f9291aedd06.png)

**[BUG 3]**
**SPRITE ERROR WITH THE CLOUD IN MINI MADNESS**
![MvL-CubbysCharacterMod-402x160-10 56PM](https://user-images.githubusercontent.com/121366826/215343810-29bd29a7-ddd0-4316-8081-448bb092dd2d.png)

**Comment by ipodtouch0218** [comment]
We do not provide support for CCM. I recommend joining the CCM discord server and reporting your issues there.

https://discord.gg/5Qu3yVSa

**Comment by CubbyCrazes** [comment]
So silly Bestie !!
