### ISSUE TITLE
Why no port on Android?

### ISSUE THREAD

**Issue by Ambijubi** [ipodtouch0218/NSMB-MarioVsLuigi#164]
I want to play this game on my smartphone with Android Marshmello, but there is no smartphone version. 
Why does no one do that?
Create port for Android, if you can, please.

**Comment by shadowkiller900** [comment]
https://discord.com/channels/956396409731551263/1080370392172073040 download it from here

**Comment by Galactidot** [comment]
can't discord.. google drive download available?
(and it's not because I'm below 13. It's because overprotective parents.)

**Comment by Ambijubi** [comment]
> https://discord.com/channels/956396409731551263/1080370392172073040 download it from here

Thank you very much! :-D
