### ISSUE TITLE
was i too annoying

### ISSUE THREAD

**Issue by borjita2019** [ipodtouch0218/NSMB-MarioVsLuigi#165]
i think i was annoying?? (not really an issue within the game)

![image](https://user-images.githubusercontent.com/63255187/219879346-16b11a27-3a12-48ef-bcf0-929793f872e8.png)

**Comment by M3KAI5ER44** [comment]
**(tl;dr: The discord server is not relevant as an issues report. I am not a moderator; however, it should be known that this is not the correct place for this.)**

I'm no expert here, but I don't think this qualifies as an issue report. Like you said, it isn't really an issue with the game, therefore, it likely shouldn't be posted here on its GitHub page, as it is not relevant to it. 
Though I am not a moderator or anything here, so it is not my job to tell you, however I _am_ saying this person to person, just to give you a heads up.

A GitHub issue report is a way to tell the developers of something like this game or software (computer apps, etc.) about bugs or things that make the app not function properly or things that could potentially be improved.

Don't worry however, you can just delete or close this issue report if you feel it isn't relevant.

**Comment by borjita2019** [comment]
> **(tl;dr: The discord server is not relevant as an issues report. I am not a moderator; however, it should be known that this is not the correct place for this.)**
> 
> I'm no expert here, but I don't think this qualifies as an issue report. Like you said, it isn't really an issue with the game, therefore, it likely shouldn't be posted here on its GitHub page, as it is not relevant to it. Though I am not a moderator or anything here, so it is not my job to tell you, however I _am_ saying this person to person, just to give you a heads up.
> 
> A GitHub issue report is a way to tell the developers of something like this game or software (computer apps, etc.) about bugs or things that make the app not function properly or things that could potentially be improved.
> 
> Don't worry however, you can just delete or close this issue report if you feel it isn't relevant.

where else can i POSSIBLY post this?
