### ISSUE TITLE
related to discord cus you won't ever read my messages

### ISSUE THREAD

**Issue by Emayeah** [ipodtouch0218/NSMB-MarioVsLuigi#189]
joris is abusive
![Screenshot_20230528_091904_Discord](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/assets/84565620/a6c60e35-6033-4f8e-bdcc-197b6814ac13)
pls lift the mute

**Comment by Emayeah** [comment]
![Screenshot_20230528_092734_Discord](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/assets/84565620/830734f0-21f3-48c5-8eb4-f18cf8e842aa)

he is just biased

**Comment by Emayeah** [comment]
please do something

**Comment by ipodtouch0218** [comment]
The issues page is for issues relating to the game itself, not the discord. Don't post here just because you don't like the answer you got after dm'ing us.
