### ISSUE TITLE
Collisions bug

### ISSUE THREAD

**Issue by eros71-dev** [ipodtouch0218/NSMB-MarioVsLuigi#30]
If you jump over the other player while he's inside the 1 block gap you can make them go through the wall and the semi-solid platforms.

![imagen](https://user-images.githubusercontent.com/16540103/172497144-a1e8866b-3f29-45a6-bae4-a39ab7136058.png)

**Comment by ipodtouch0218** [comment]
Should finally be fixed with release 1.6.4.0b-beta
