### ISSUE TITLE
Visible Borders in Sky Level's Background

### ISSUE THREAD

**Issue by Ram1tas** [ipodtouch0218/NSMB-MarioVsLuigi#31]
Haven't checked to see if this is an issue in other levels with a scrolling background, but the sky level has a small, yet visible, gap in its background image. 

https://user-images.githubusercontent.com/106049729/173211269-162f9b6d-d92c-401a-9cf2-c1c98604bd50.mp4

**Comment by ipodtouch0218** [comment]
Fixed in v1.6.0.1-beta
