### ISSUE TITLE
Players can become stuck when wedged into small spaces

### ISSUE THREAD

**Issue by CosmicTailz** [ipodtouch0218/NSMB-MarioVsLuigi#38]
https://user-images.githubusercontent.com/89882863/177045886-0f2982e9-71ca-4f91-b5b4-b87cd4adca80.mp4

I'm not sure how this happened since I wasn't nearby when it occurred, but players can get stuck in a falling animation after being hit by another player if they're close to a small gap like the one shown.

If a player is in this state, they continuously vibrate in place while being unable to control their character in any way. Since they are seemingly intangible to player interaction, the only ways they can get unstuck are by another player throwing bob-ombs at them until they die and respawn, or by leaving the room.

**Comment by ipodtouch0218** [comment]
Fixed in v1.6.6.0-beta
