### ISSUE TITLE
Linux Info Displays are Misaligned and Unreadable

### ISSUE THREAD

**Issue by WHALEINATOR** [ipodtouch0218/NSMB-MarioVsLuigi#40]
Linux version’s text boxes for indicating star amount fraction (ie 2/8 at the top left of gameplay) and also the coin amount at the top right are both vertically misaligned. The star count is unreadable

**Comment by Marioiscool246** [comment]
I was about to post this same issue as I have this problem too.

**Comment by Marioiscool246** [comment]
![Picture](https://user-images.githubusercontent.com/27823923/177544214-2fd3f6ac-8aee-437d-b49d-45f569b7007d.jpg)

**Comment by BigClarky** [comment]
Can confirm this happens running on 64-bit Ubuntu 22.04 LTS for both 1.6.6.1-beta and 1.6.7.0-beta

**Comment by TheDylanArts** [comment]
I can confirm this issue. Clock, Star count, Lives, Coin count, And the red arrow on the mini map are all misaligned. Most of the elements are off the top of the screen it appears. 

Game version: MarioVsLuigi-Linux-v1.6.8.1-beta
Software: Kernel: x86_64 Linux 5.19.1 - OS: 64-bit Manjaro 21.3.7 - DE: GNOME 42.3 - WM: Mutter
Hardware: CPU: Intel Core i7-12700K - GPU: AMD Radeon RX 6600 XT - RAM: 64GB

**Comment by ipodtouch0218** [comment]
Fixed in v1.7.0.1-beta
