### ISSUE TITLE
Mini players kill other mini players on groundpound

### ISSUE THREAD

**Issue by abso1utezer0** [ipodtouch0218/NSMB-MarioVsLuigi#43]
When a player affected by the Mini Mushroom groundpounds another player under the same effect, the player being groundpounded is killed. In the original game, the player being groundpounded would only be knocked back and drop their stars.

**Comment by ShadowWalker13** [comment]
Mini mushrooms can kill other mini players with a ground pound in both the original and the remake

**Comment by Terravin** [comment]
Went to check this on the original game, ground pounding a mini player while mini yourself **does** kill the player who was attacked. This also happens in this version as expected.
https://user-images.githubusercontent.com/19255140/177658536-1c13b015-ef5a-402a-ace5-cbfa77c78567.mp4

**Comment by oddvar812** [comment]
you don't loose 3 stars by getting ground pounded while you're mini in the DS version though
