### ISSUE TITLE
Setting Counts

### ISSUE THREAD

**Issue by Mardz38** [ipodtouch0218/NSMB-MarioVsLuigi#55]
Would like for the **Coins for Powerup** be able to go all the way up to 99 just like the stars. Or just make all settings higher than 99.
Maybe 255?

**Comment by ShadowWalker13** [comment]
The max coin count was set to 8 due to issues with higher values. I believe this is planned to change

**Comment by ipodtouch0218** [comment]
Changed coins for item limit to 99 in v1.6.6.0-beta

Why would you ever want 255 stars/coins???

**Comment by Mardz38** [comment]
Sorry, didn't know you needed more sprites for the 99 coins.
I wanted it for more chaos/longer games.
255 because I'm unfamiliar with unity and don't know if it had byte limits or something.
