### ISSUE TITLE
Massive Slowdown on Menus

### ISSUE THREAD

**Issue by SQUISHY6094** [ipodtouch0218/NSMB-MarioVsLuigi#65]
On version 1.6.5.0 and up, I've noticed a lot of slowdown on specifically the menus.
Once in a game it runs fine, but afterwards it goes back to averaging out at 1-2 fps.
I'm using the Win-64 Version, And I commonly open the game through Steam.

![image](https://user-images.githubusercontent.com/74333752/178391882-5e8d81e9-b520-4f4f-8bcc-2ce1fee4bd58.png)

**Comment by ipodtouch0218** [comment]
does this happen with the 32 bit variant, or the WebGL build?

**Comment by souxd** [comment]
i have the same issue on linux. I dont really know what the problem is XD

**Comment by ipodtouch0218** [comment]
Closing as stale. If this is still an issue, please provide more information (such as a player.log, your operating system, etc.)
