### ISSUE TITLE
Lobbies go missing

### ISSUE THREAD

**Issue by AbelSuperstar100** [ipodtouch0218/NSMB-MarioVsLuigi#66]
On the versions I have played on (v1.6.4.0b-v1.6.6.1), moving from any of the server and going back makes the list of available lobbies go blank, like no one is online playing. I use the Win-64 version.

https://user-images.githubusercontent.com/56049266/178597405-7e18c58d-c6ad-4030-b538-f30a13912554.mp4

**Comment by ipodtouch0218** [comment]
Known issue, already fixed in nightly builds. Will be fixed in next release.

**Comment by ipodtouch0218** [comment]
Fixed in [v1.6.7.0 release](https://github.com/ipodtouch0218/NSMB-MarioVsLuigi/releases/tag/v1.6.7.0-beta)
