### ISSUE TITLE
Chmod required for Mac Client

### ISSUE THREAD

**Issue by EmeraldLoc** [ipodtouch0218/NSMB-MarioVsLuigi#67]
For some reason, the app won't launch, however, this can be fixed. By running `cd /Applications/MarioVsLuigi-MacOS.app/Contents/MacOS`, then running `chmod +x NSMB-MarioVsLuigi` You can launch the game and it works fine. To fix this, during build time, simply make sure the executable file is a executable

**Comment by ipodtouch0218** [comment]
It's not really doable, since I'm on Windows and it doesn't support unix file permissions. Same problem happens with the Linux builds.
