### ISSUE TITLE
UI on Linux build is bugged

### ISSUE THREAD

**Issue by Poyochan1** [ipodtouch0218/NSMB-MarioVsLuigi#75]
The UI on the Linux build of this game appears to misplaced for whatever reason
![Screenshot from 2022-07-19 18-59-09](https://user-images.githubusercontent.com/109632592/179862660-af1e651d-06a1-4f48-995b-1fe163587eb5.png)

**Comment by ipodtouch0218** [comment]
Duplicate of #40
